### ISSUE TITLE
Problem with axis order and direction in BBOX parameter

### ISSUE THREAD

**Issue by edigiacomo** [ecmwf/skinnywms#1]
First of all, thank you for skinnywms!

Unfortunately, it seems that the server has some problems with the axis order and direction in the `BBOX` parameter.

- In WMS < 1.3.0, the axis order and direction in `BBOX` are always `left,bottom,right,top`:
  - In `EPSG:4326` the order is `min_lon,min_lat,max_lon,max_lat`
  - In `EPSG:3857` the order is `min_x,min_y,max_x,max_y`

- In WMS 1.3.0, the axis order and direction in `BBOX` depend on the spatial reference:
  - In `EPSG:4326` the order is `min_lat,min_lon,max_lat,max_lon`
  - In `EPSG:3857` the order is `min_x,min_y,max_x,max_y`

If I understand correctly, skinnywms considers every `BBOX` as
`min_lat,min_lon,max_lat,max_lon`. With `EPSG:4326` and WMS 1.3.0 everything
works fine, but e.g. with `EPSG:4326` and WMS 1.1.1 the tiles are wrongly placed.

References:

- [WMS 1.1.1 Implementation Specification](http://portal.opengeospatial.org/files/?artifact_id=1081&version=1&format=pdf) (paragraph "6.5.6 - Bounding Box")
- [WMS 1.3.1 Implementation Specification](http://portal.opengeospatial.org/files/?artifact_id=14416) (paragraph "6.7.4 - Bounding boxes")
- [EPSG registry](http://www.epsg-registry.org)

**Comment by sylvielamythepaut** [comment]
Hi,

I have just committed a change that should fix this issue.
Please, tell me how it goes, and if everything is fine we can close the issue

**Comment by edigiacomo** [comment]
Thank you for the quick fix.

Everything works fine now with EPSG:4326 (both WMS 1.1.1 and WMS 1.3.0). With EPSG:3857 is not working, but I'll open another issue to track this latter problem, because the problem is different: the axis order in EPSG:3857 is correct but I suspect that `macro.mmap` needs a bbox in lat/lon instead of meters.
