### ISSUE TITLE
Temporary files management

### ISSUE THREAD

**Issue by brancomat** [ecmwf/skinnywms#10]
If I'm not mistaken the temporary files (`wms-server-????????.png`) are not deleted nor reused once served, this could trigger some disk space issues in the long run.

It would be also great to have the possibility of optionally configure the tmp dir (e.g. for assigning it to a `/dev/shm` device for performance enhancement)

**Comment by sylvielamythepaut** [comment]
This will be a very nice improvement.

**Comment by brancomat** [comment]
I've submitted a pull request for the temporary files cleanup.

About reassigning the path (e.g.: to `/dev/shm`), quoting the doc of the `tempfile` python library used for the temporary files:
> The default directory is chosen from a platform-dependent list, but the user of the application can control the directory location by setting the TMPDIR, TEMP or TMP environment variables. 
(from: https://docs.python.org/3.6/library/tempfile.html)

I can confirm that on unix systems exporting the `TEMP` variable permits to relocate the temporary files path. If this is enough (it is for me) this issue may be closed (maybe referencing this in the `README` of the project?)

**Comment by sylvielamythepaut** [comment]
Hi,
We had a closer look at this issue and found the bug, we  think that there was a simpler solution that the one you suggested and implemented it .. I just merged it .. Hope it will solve tour problem ,and it should allow us to add a bit of caching if we need later, still in discussion here 
Thanks,
Sylvie
